-- INSERT INTO user_account (id, email, login, password) VALUES('1','johny@icloud.com', 'johny', 'johny1');
-- INSERT INTO user_account (id, email, login, password) VALUES('2', 'stacy@icloud.com', 'stacy', 'stacy2');
-- INSERT INTO user_account (id, email, login, password) VALUES('3', 'smith@gmail.com', 'smith', 'smith3');
-- INSERT INTO user_account (id, email, login, password) VALUES('4','george@hotmail.com', 'george', 'george4');
-- INSERT INTO user_account (id, email, login, password) VALUES('5', 'barbra@gmail.com', 'barbra', 'barbra5');
-- INSERT INTO user_account (id, email, login, password) VALUES('6', 'jan@gmail.com', 'jan', 'jan1');